mcp-server:
  address: "127.0.0.1:18232"

logger:
  path: "./logs" # 日志文件路径。默认为空，表示关闭，仅输出到终端
  file: "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"
  prefix: "ai-mcp" # 日志内容输出前缀。默认为空
  level: "all" # 日志输出级别
  timeFormat: "2006-01-02 15:04:05" # 自定义日志输出的时间格式，使用Golang标准的时间格式配置
  ctxKeys: [] # 自定义Context上下文变量名称，自动打印Context的变量到日志中。默认为空
  header: true # 是否打印日志的头信息。默认true
  stdout: true # 日志是否同时输出到终端。默认true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    type: "mysql"
    link: "root:xxx@tcp(127.0.0.1:3306)/xxx?charset=utf8mb3&parseTime=true&loc=Local"
    prefix: ""
    createdAt: "createTime"
    updatedAt: "updateTime"
    debug: true

# 数据库操作配置
dbConfig:
  readonly: false  # 是否启用只读模式，true表示只允许查询操作，false表示允许所有操作
